# <b><span style='color:#F1A424'>AutoChurn - Bank Churn Prediction</span> </b>

### Disclaimer
The sample code (“Sample Code”) provided is not covered by any Teradata agreements. Please be aware that Teradata has no control over the model responses to such sample code and such response may vary. The use of the model by Teradata is strictly for demonstration purposes and does not constitute any form of certification or endorsement. The sample code is provided “AS IS” and any express or implied warranties, including the implied warranties of merchantability and fitness for a particular purpose, are disclaimed. In no event shall Teradata be liable for any direct, indirect, incidental, special, exemplary, or consequential damages (including, but not limited to, procurement of substitute goods or services; loss of use, data, or profits; or business interruption) sustained by you or a third party, however caused and on any theory of liability, whether in contract, strict liability, or tort arising in any way out of the use of this sample code, even if advised of the possibility of such damage.

## <b> Problem overview:</b>

**Dataset used - Bank Churn Dataset**

**Features**:

- `customer_id`: customer_id .
- `credit_score`: credit score of customer.
- `country`: country of customer.
- `gender`: Gender of customer.
- `age`: Age of customer.
- `tenure`: tenure.
- `balance`: bank balance.
- `products_number`: products number.
- `credit_card`: having credit card or not.
- `active_member`: active member or not.
- `estimated_salary`: Estimated salary of customer..

**Target Variable**:

- `churn`: 1 if the client has left the bank during some period or 0 if he/she has not.

        
**Objective**:

The primary objective is typically to build a model that can accurately predict the Customer Churn for ABC Bank.

**Usecase**:

Here, we will use AutoChurn(Automated Machine Learning for Churn Prediction) functionality to automate the entire process of developing a predictive model. It will perform feature exploration, feature engineering, data preparation, model training and evaluation on dataset in auto run and at end we will get leaderboard containined different models along with their performance. Model will also have rank associated with them which indicates which is best performing model for given data followed by other models.

In [1]:
# Importing other important libraries
import getpass
from teradataml import create_context, display

display.enable_ui = False

In [2]:
import warnings
warnings.filterwarnings("ignore")

In [3]:
host = getpass.getpass("Host: ")
username = getpass.getpass("Username: ")
password = getpass.getpass("Password: ")

ctx = create_context(host=host, username=username, password=password)

## <b><span style='color:#F1A424'>| 1.</span> Loading Deployed Models - 'top_10_models' </b>

### <b><span style='color:#F1A424'>| 1.1.</span> Loading Model </b>

In [4]:
# Creating AutoML object

aml=ctx.AutoChurn()

In [5]:
# Loading models

models_1 = aml.load('top_10_models')

In [6]:
# Display loaded models

models_1

,RANK,MODEL_ID,FEATURE_SELECTION,ACCURACY,MICRO-PRECISION,MICRO-RECALL,MICRO-F1,MACRO-PRECISION,MACRO-RECALL,MACRO-F1,WEIGHTED-PRECISION,WEIGHTED-RECALL,WEIGHTED-F1,DATA_TABLE
0,1,KNN_0,rfe,0.859835,0.859835,0.859835,0.859835,0.860249,0.859828,0.859793,0.860244,0.859835,0.859794,automl__churn_rfe_179283000806482
1,2,KNN_4,rfe,0.859442,0.859442,0.859442,0.859442,0.859572,0.859439,0.859429,0.859569,0.859442,0.859429,automl__churn_rfe_179283000806482
2,3,KNN_3,pca,0.834707,0.834707,0.834707,0.834707,0.835057,0.834701,0.834663,0.835053,0.834707,0.834664,automl__churn_pca_179283650091934
3,4,KNN_7,pca,0.833137,0.833137,0.833137,0.833137,0.833363,0.833132,0.833107,0.833359,0.833137,0.833108,automl__churn_pca_179283650091934
4,5,XGBOOST_2,rfe,0.822144,0.822144,0.822144,0.822144,0.822232,0.822140,0.822130,0.822230,0.822144,0.822131,automl__churn_rfe_179283000806482
5,6,XGBOOST_0,rfe,0.819788,0.819788,0.819788,0.819788,0.830875,0.819752,0.818254,0.830852,0.819788,0.818260,automl__churn_rfe_179283000806482
6,7,DECISIONFOREST_0,rfe,0.811936,0.811936,0.811936,0.811936,0.822921,0.811972,0.810335,0.822944,0.811936,0.810328,automl__churn_rfe_179283000806482
7,8,DECISIONFOREST_2,rfe,0.811936,0.811936,0.811936,0.811936,0.822921,0.811972,0.810335,0.822944,0.811936,0.810328,automl__churn_rfe_179283000806482
8,9,XGBOOST_3,pca,0.808009,0.808009,0.808009,0.808009,0.808630,0.808001,0.807910,0.808624,0.808009,0.807912,automl__churn_pca_179283650091934
9,10,XGBOOST_1,pca,0.795053,0.795053,0.795053,0.795053,0.804655,0.795018,0.793412,0.804634,0.795053,0.793419,automl__churn_pca_179283650091934

In [7]:
### Loading Dataset for Prediction

ctx.load_example_data('teradataml','bank_churn')
df = ctx.DataFrame('bank_churn')

WARNING: Skipped loading table bank_churn since it already exists in the database.

In [8]:
# Display data

df

             credit_score  country  gender  age  tenure    balance  products_number  credit_card  active_member  estimated_salary  churn
customer_id
15688963              731   France  Female   52      10       0.00                1            1              1          24998.75      1
15603582              569    Spain  Female   34       3       0.00                1            1              0         133997.53      0
15618203              773  Germany    Male   51       8  116197.65                2            1              1          86701.40      0
15809826              728   France  Female   46       2  109705.52                1            1              0          20276.87      1
15668775              757   France    Male   47       3  130747.10                1            1              0         143829.54      0
15704053              710    Spain    Male   62       3  131078.42                2            1              0         119348.76      1
15583863              681  Germany    Male   49       8  142946.18                1            0              0         187280.51      1
15679909              665    Spain    Male   41       8       0.00                2            1              0         132152.32      0
15609618              721  Germany    Male   28       9  154475.54                2            0              1         101300.94      1
15806808              834  Germany  Female   57       8  112281.60                3            1              0         140225.14      1

In [9]:
df.shape

(10000, 12)

### <b><span style='color:#F1A424'>| 1.2.</span> Generating Prediction & Performance Metrics</b>

In [10]:
# Generate prediction using some data rows and model rank

prediction = aml.predict(df.iloc[:80], rank=1)

In [11]:
prediction

   automl_id  prediction    prob_1    prob_0  churn
0         82           0  1.000000  0.000000      0
1         50           0  1.000000  0.000000      0
2        186           0  0.710003  0.289997      1
3         42           1  0.314685  0.685315      0
4         66           0  1.000000  0.000000      0
5        114           0  0.686544  0.313456      0
6         34           0  1.000000  0.000000      0
7        106           1  0.337121  0.662879      0
8         74           0  1.000000  0.000000      0
9        122           1  0.319625  0.680375      0

In [12]:
# Generate performance metrics

performance_metric = aml.evaluate(df.iloc[:80], rank=1)

In [13]:
performance_metric

############ output_data Output ############

   SeqNum              Metric  MetricValue
0       3        Micro-Recall     0.725000
1       5     Macro-Precision     0.616667
2       6        Macro-Recall     0.625448
3       7            Macro-F1     0.620362
4       9     Weighted-Recall     0.725000
5      10         Weighted-F1     0.729983
6       8  Weighted-Precision     0.735833
7       4            Micro-F1     0.725000
8       2     Micro-Precision     0.725000
9       1            Accuracy     0.725000


############ result Output ############

       Prediction  Mapping  CLASS_1  CLASS_2  Precision    Recall        F1  Support
SeqNum
1               1  CLASS_2       12        8   0.400000  0.444444  0.421053       18
0               0  CLASS_1       50       10   0.833333  0.806452  0.819672       62

In [14]:
# Generate prediction using data and model rank

prediction = aml.predict(df.iloc[:80], rank=7)

In [15]:
prediction

   automl_id  prediction  prob_1  prob_0  churn
0        395           0     0.0     1.0      0
1        475           0     0.0     1.0      0
2        491           0     0.0     1.0      0
3        507           0     0.0     1.0      1
4        603           0     0.0     1.0      0
5        611           0     0.0     1.0      0
6        147           1     1.0     0.0      1
7        347           1     1.0     0.0      1
8        523           1     1.0     0.0      1
9        595           0     0.0     1.0      0

In [16]:
# Generate performance metrics

performance_metric = aml.evaluate(df.iloc[:80], rank=7)

In [17]:
performance_metric

############ output_data Output ############

   SeqNum              Metric  MetricValue
0       3        Micro-Recall     0.787500
1       5     Macro-Precision     0.687141
2       6        Macro-Recall     0.646057
3       7            Macro-F1     0.659915
4       9     Weighted-Recall     0.787500
5      10         Weighted-F1     0.774481
6       8  Weighted-Precision     0.768915
7       4            Micro-F1     0.787500
8       2     Micro-Precision     0.787500
9       1            Accuracy     0.787500


############ result Output ############

       Prediction  Mapping  CLASS_1  CLASS_2  Precision    Recall        F1  Support
SeqNum
1               1  CLASS_2        6        7   0.538462  0.388889  0.451613       18
0               0  CLASS_1       56       11   0.835821  0.903226  0.868217       62

## <b><span style='color:#F1A424'>| 2.</span> Loading Deployed Models - 'mixed_models' </b>

### <b><span style='color:#F1A424'>| 2.1.</span> Loading Model </b>

In [18]:
churn = ctx.AutoChurn()

In [19]:
# Loading models

models_2 = churn.load('mixed_models')

In [20]:
models_2

,RANK,MODEL_ID,FEATURE_SELECTION,ACCURACY,MICRO-PRECISION,MICRO-RECALL,MICRO-F1,MACRO-PRECISION,MACRO-RECALL,MACRO-F1,WEIGHTED-PRECISION,WEIGHTED-RECALL,WEIGHTED-F1,DATA_TABLE
0,1,KNN_4,rfe,0.859442,0.859442,0.859442,0.859442,0.859572,0.859439,0.859429,0.859569,0.859442,0.859429,automl__churn_rfe_179289051111691
1,2,XGBOOST_2,rfe,0.822144,0.822144,0.822144,0.822144,0.822232,0.822140,0.822130,0.822230,0.822144,0.822131,automl__churn_rfe_179289051111691
2,3,XGBOOST_0,rfe,0.819788,0.819788,0.819788,0.819788,0.830875,0.819752,0.818254,0.830852,0.819788,0.818260,automl__churn_rfe_179289051111691
3,4,XGBOOST_3,pca,0.808009,0.808009,0.808009,0.808009,0.808630,0.808001,0.807910,0.808624,0.808009,0.807912,automl__churn_pca_179282113444905

### <b><span style='color:#F1A424'>| 2.2.</span> Generating Prediction & Performance Metrics</b>

In [21]:
# Generate prediction using data and model rank

prediction = churn.predict(df.iloc[:80], rank=4)

In [22]:
prediction

   automl_id  Prediction    Prob_1    Prob_0  churn
0        360           1  0.607720  0.392280      1
1        392           0  0.333619  0.666381      0
2        520           1  0.718440  0.281560      1
3        440           0  0.454460  0.545540      0
4        472           1  0.544298  0.455702      0
5         40           1  0.740910  0.259090      0
6        592           0  0.401336  0.598664      0
7        344           1  0.778720  0.221280      1
8        144           1  0.694799  0.305201      1
9        288           0  0.400431  0.599569      0

In [23]:
# Generate performance metrics

performance_metric = churn.evaluate(df.iloc[:80], rank=4)

In [24]:
performance_metric

############ output_data Output ############

   SeqNum              Metric  MetricValue
0       3        Micro-Recall     0.750000
1       5     Macro-Precision     0.693333
2       6        Macro-Recall     0.759857
3       7            Macro-F1     0.702381
4       9     Weighted-Recall     0.750000
5      10         Weighted-F1     0.767857
6       8  Weighted-Precision     0.818000
7       4            Micro-F1     0.750000
8       2     Micro-Precision     0.750000
9       1            Accuracy     0.750000


############ result Output ############

       Prediction  Mapping  CLASS_1  CLASS_2  Precision    Recall        F1  Support
SeqNum
0               0  CLASS_1       46        4   0.920000  0.741935  0.821429       62
1               1  CLASS_2       16       14   0.466667  0.777778  0.583333       18

## <b><span style='color:#F1A424'>| 3.</span> Loading Deployed Models - 'range_models' </b>

### <b><span style='color:#F1A424'>| 3.1.</span> Loading Model</b>

In [25]:
# Creating another AutoML object

obj=ctx.AutoChurn()

In [26]:
# Loading models

models_3 = obj.load('range_models')

In [27]:
models_3

,RANK,MODEL_ID,FEATURE_SELECTION,ACCURACY,MICRO-PRECISION,MICRO-RECALL,MICRO-F1,MACRO-PRECISION,MACRO-RECALL,MACRO-F1,WEIGHTED-PRECISION,WEIGHTED-RECALL,WEIGHTED-F1,DATA_TABLE
0,1,DECISIONFOREST_2,rfe,0.811936,0.811936,0.811936,0.811936,0.822921,0.811972,0.810335,0.822944,0.811936,0.810328,automl__churn_rfe_179282226550177
1,2,XGBOOST_3,pca,0.808009,0.808009,0.808009,0.808009,0.808630,0.808001,0.807910,0.808624,0.808009,0.807912,automl__churn_pca_179284648828801
2,3,XGBOOST_1,pca,0.795053,0.795053,0.795053,0.795053,0.804655,0.795018,0.793412,0.804634,0.795053,0.793419,automl__churn_pca_179284648828801
3,4,DECISIONFOREST_1,pca,0.794268,0.794268,0.794268,0.794268,0.797081,0.794287,0.793787,0.797092,0.794268,0.793783,automl__churn_pca_179284648828801

### <b><span style='color:#F1A424'>| 3.2.</span> Generating Prediction & Performance Metrics</b>

In [28]:
# Generate prediction using data and model rank

prediction = obj.predict(df.iloc[:80], rank=1)

In [29]:
prediction

   automl_id  prediction  prob_1  prob_0  churn
0        523           1     1.0     0.0      1
1         43           1     1.0     0.0      0
2         35           0     0.0     1.0      0
3        235           0     0.0     1.0      0
4        355           0     0.0     1.0      0
5        547           0     0.0     1.0      0
6        291           0     0.0     1.0      0
7        363           0     0.0     1.0      1
8        395           0     0.0     1.0      0
9        443           0     0.0     1.0      0

In [30]:
# Generate performance metrics

performance_metric = obj.evaluate(df.iloc[:80], rank=1)

In [31]:
performance_metric

############ output_data Output ############

   SeqNum              Metric  MetricValue
0       3        Micro-Recall     0.787500
1       5     Macro-Precision     0.687141
2       6        Macro-Recall     0.646057
3       7            Macro-F1     0.659915
4       9     Weighted-Recall     0.787500
5      10         Weighted-F1     0.774481
6       8  Weighted-Precision     0.768915
7       4            Micro-F1     0.787500
8       2     Micro-Precision     0.787500
9       1            Accuracy     0.787500


############ result Output ############

       Prediction  Mapping  CLASS_1  CLASS_2  Precision    Recall        F1  Support
SeqNum
1               1  CLASS_2        6        7   0.538462  0.388889  0.451613       18
0               0  CLASS_1       56       11   0.835821  0.903226  0.868217       62

In [32]:
ctx.remove_context()

True